apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fstack-be
spec:
  selector:
    matchLabels:
      app: fstack-be
  replicas: 2
  template:
    metadata:
      labels:
        app: fstack-be
    spec:
      containers:
      - name: fstack-be
        image: 192.168.49.2:5000/fstack-be
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fstack-be
  labels:
    app: fstack-be
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: fstack-be
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-configmap
data:
  default.conf: |
    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 80;
        server_name localhost;

        location /api {
            proxy_pass http://fstack-be:8000; # Forward requests to Gunicorn
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Example for serving static files (optional)
        location / {
            alias /usr/share/nginx/html/;
        }
    }
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fstack-fe
spec:
  selector:
    matchLabels:
      app: fstack-fe
  replicas: 2
  template:
    metadata:
      labels:
        app: fstack-fe
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-conf-configmap
      initContainers:
      - name: fstack-fe-dist
        image: 192.168.49.2:5000/fstack-fe
        command: ["sh", "-c", "cp -r /app/dist/* /shared-data/"]
        volumeMounts:
          - name: shared-data
            mountPath: /shared-data

      containers:

      - name: fstack-fe-nginx
        image: nginx
        volumeMounts:
          - name: shared-data
            mountPath: /usr/share/nginx/html
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fstack-fe
  labels:
    app: fstack-fe
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: fstack-fe