gitea:
  config:
    server:
      DOMAIN: gitea-local
      SSH_DOMAIN: gitea-local
      ROOT_URL: http://gitea-local/
    webhook:
      ALLOWED_HOST_LIST: "*"
valkey:
  enabled: true
valkey-cluster:
  enabled: false
postgresql-ha:
  enabled: false
postgresql:
  enabled: true
