apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingress
  annotations:
spec:
  rules:
  - host: gitea-local # FOR BROWSER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea-http # ClusterIP
            port:
              number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-local
  labels:
    app: gitea
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: gitea
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone-ingress
  annotations:
spec:
  rules:
  - host: drone.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drone
            port:
              number: 8080
