apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fstack-fe
spec:
  selector:
    matchLabels:
      app: fstack-fe
  replicas: 2
  template:
    metadata:
      labels:
        app: fstack-fe
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-conf-configmap

      containers:

      - name: fstack-fe
        image: 192.168.49.2:5000/fstack-fe:latest
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/
        resources:
          requests:
            cpu: 50m  # Nginx 通常需要较少 CPU
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 1
          timeoutSeconds: 2
          failureThreshold: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: fstack-fe
  labels:
    app: fstack-fe
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fstack-fe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fstack-ingress
  annotations:
    # 可选：如果您需要更复杂的重写规则，可以使用这些注解
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls: # 添加 TLS 配置
  - hosts:
    - fstack.local
    secretName: fstack-local-tls # 指向刚才创建的 Secret
  rules:
  # 定义规则1：使用自定义域名（需要通过hosts文件解析）
  - host: fstack.local # 您喜欢的任何域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fstack-fe  # 指向您的前端 Service
            port:
              number: 80   # 前端 Service 的端口
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fstack-be  # 指向您的后端 Service
            port:
              number: 8000   # 后端 Service 的端口